server:
  port: 8084
  error:
    include-message: always
spring:
  application:
    name: service-credits
  data:
    mongodb:
      database: BankCreditsDB
      auto-index-creation: true
      host: localhost
      port: 27017
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9093/eureka
message:
  demo: leido desde local