server:
  port: 8084
  error:
    include-message: always
spring:
  application:
    name: service-credits
  data:
    mongodb:
      database: BankCreditsDB
      auto-index-creation: true
      host: localhost
      port: 27017
  config:
    import: optional:configserver:http://localhost:8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9093/eureka
resilience4j:
  circuitbreaker:
    instances:
      credit:
        failureRateThreshold: 50
        minimumNumberOfCalls: 4
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 8
        waitDurationInOpenState: 50s
        permittedNumberOfCallsInHalfOpenState: 3
message:
  demo: leido desde local